version: "3.9"

# Create a docker compose file for a Nextjs app

services:
  # Create a service for the Nextjs app
  app:
    build:
        context: .
        dockerfile: Dockerfile
        target: dev
    ports:
      - "3000:3000"
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next

  # Create a service for the database
  db:
    # Use the official Postgres image
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    # Expose port 5432
    ports:
      - "5432:5432"
    # Set the environment variables
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - "8080:8080"


volumes:
    db_data: