import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {io} from "socket.io-client";
import {useEffect, useState} from "react";

let socket;
export default function Home() {
    const [number1, setNumber1] = useState(0)
    const [number2, setNumber2] = useState(0)
    const [result, setResult] = useState(0)
    useEffect(() => {
        const SocketHandler = async () => {
            await fetch('/api/socket');
            socket = io();

            socket.on('connect', () => {
                console.log('connected')
            });
            socket.on('result', async (result) => {
                await setResult(result)
            });

        };
        SocketHandler();

        return () => {
            if (socket) {
                socket.disconnect();
            }
        };
    }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App + Socket IO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <input type={"number"} value={number1} onInput={(event) => setNumber1(event.target.valueAsNumber)}/>
        <input type={"number"} value={number2} onInput={(event) => setNumber2(event.target.valueAsNumber)}/>
        <button onClick={() => socket.emit('input-submit', number1, number2)}>Send</button>
          <button onClick={() => socket.emit('message-sent', 'Hello World')}>Send Message</button>
        <p>{result}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
